"""Write the PRISMA-ScR report from the data files, and refuse to fudge it.

    python -m src.lit.report

The flow has to reconcile: every record retrieved is either a duplicate, or
excluded at screening, or has no retrievable text, or reached extraction. When
the arithmetic does not close, this module prints the discrepancy and exits
non-zero rather than adjusting a number to make the diagram tidy. A scoping
review whose flow does not add up is telling the reader something, and the
something is usually a bug in the pipeline rather than a fact about the
literature.

Everything printed here comes from a file on disk. No count is typed in by hand,
which is why the report can be regenerated after a requeue without anyone
remembering what the old numbers were.
"""

from __future__ import annotations

import io
import json
import os
import sys
from collections import Counter, defaultdict

from .reliability import cohens_kappa, interpret

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LIT = os.path.join(ROOT, "data", "lit")
REPORT = os.path.join(ROOT, "docs", "scoping", "report.md")


def load_jsonl(name: str) -> list[dict]:
    path = os.path.join(LIT, name)
    if not os.path.exists(path):
        return []
    rows = []
    with io.open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def load_json(name: str) -> dict:
    path = os.path.join(LIT, name)
    if not os.path.exists(path):
        return {}
    with io.open(path, encoding="utf-8") as fh:
        return json.load(fh)


def main() -> int:
    search_log = load_json("search-log.json")
    queries = load_json("queries.json")
    frozen = load_json("protocol-frozen.json")
    records = load_jsonl("records.jsonl")
    verdicts = load_jsonl("screen/verdicts.jsonl")
    included = load_jsonl("screened-in.jsonl")
    retrieval = load_jsonl("retrieval.jsonl")
    schemes = load_jsonl("schemes.jsonl")
    rejected = load_jsonl("extract/rejected.jsonl")
    ft_excluded = load_jsonl("fulltext-excluded.jsonl")

    if not records:
        print("no records; nothing to report")
        return 1

    lines: list[str] = []
    add = lines.append

    add("# Scoping review of category schemes for AI disclosure: report")
    add("")
    add("Generated by `python -m src.lit.report`. Every figure comes from a file in")
    add("`data/lit/`; none is typed in. Regenerate rather than edit.")
    add("")
    if frozen:
        add(f"Protocol frozen {frozen.get('frozen_at', 'unknown')}, sha256 "
            f"`{frozen.get('protocol', {}).get('sha256', '')[:16]}`. "
            f"Queries sha256 `{frozen.get('queries', {}).get('sha256', '')[:16]}`.")
        add("")

    # ---------------------------------------------------------------- flow
    screened = {row["rec_id"] for row in verdicts}
    unscreened = len(records) - len(screened)
    included_ids = {row["rec_id"] for row in included}
    excluded_at_screening = len(screened) - len(included_ids)
    retrieval_by_status = Counter(row["status"] for row in retrieval)
    no_text = retrieval_by_status.get("no_text", 0)
    reached_extraction = len(retrieval) - no_text
    ft_excluded_count = len(ft_excluded)
    schemes_kept = {row["scheme_id"] for row in schemes}
    papers_with_scheme = {row["rec_id"] for row in schemes}

    add("## 1. Flow")
    add("")
    add("| Stage | Records |")
    add("|---|---:|")
    add(f"| Returned by the frozen queries, before deduplication | "
        f"{search_log.get('records_returned_total', 0)} |")
    add(f"| Merged as duplicates | {search_log.get('duplicates_merged', 0)} |")
    add(f"| Unique records | {len(records)} |")
    add(f"| Screened on title and abstract | {len(screened)} |")
    add(f"| Excluded at screening | {excluded_at_screening} |")
    add(f"| Included after screening | {len(included_ids)} |")
    add(f"| Text not retrievable | {no_text} |")
    add(f"| Reached extraction | {reached_extraction} |")
    add(f"| Excluded at full text, no scheme present | {ft_excluded_count} |")
    add(f"| Papers contributing at least one verified dimension | "
        f"{len(papers_with_scheme)} |")
    add(f"| Schemes | {len(schemes_kept)} |")
    add(f"| Verified dimension rows | {len(schemes)} |")
    add("")

    faults = []
    if unscreened:
        faults.append(f"{unscreened} unique records have no screening verdict")
    accounted = ft_excluded_count + len(papers_with_scheme)
    if retrieval and accounted != reached_extraction:
        faults.append(
            f"{reached_extraction} records reached extraction but "
            f"{ft_excluded_count} excluded at full text plus "
            f"{len(papers_with_scheme)} contributing papers is {accounted}")
    if included and retrieval and len(retrieval) != len(included_ids):
        faults.append(f"{len(included_ids)} included but {len(retrieval)} "
                      "retrieval rows")
    if faults:
        add("**The flow does not reconcile.**")
        add("")
        for fault in faults:
            add(f"- {fault}")
        add("")

    # ------------------------------------------------------------- search
    add("## 2. Search")
    add("")
    add(f"Run {search_log.get('ran_at', 'unknown')}. "
        f"{len(search_log.get('queries', []))} queries across the sources below.")
    add("")
    per_source: dict[str, list[int]] = defaultdict(lambda: [0, 0, 0])
    for row in search_log.get("queries", []):
        stats = per_source[row["source"]]
        stats[0] += 1
        stats[1] += row["returned"]
        stats[2] += row["new"]
    add("| Source | Queries | Returned | New at that point |")
    add("|---|---:|---:|---:|")
    for source, (count, returned, new) in sorted(per_source.items()):
        add(f"| {source} | {count} | {returned} | {new} |")
    add("")
    empty = [row["query_id"] for row in search_log.get("queries", [])
             if row["returned"] == 0]
    add(f"Queries that returned nothing: {', '.join(empty) if empty else 'none'}.")
    add("")
    known = [row for row in search_log.get("queries", []) if row.get("block") == "known"]
    missed = [row["query"] for row in known if row["returned"] == 0]
    add(f"Known-item searches: {len(known)} run, "
        f"{len(missed)} not found{': ' + ', '.join(missed) if missed else ''}.")
    add("")

    # ---------------------------------------------------------- screening
    add("## 3. Screening")
    add("")
    by_rec: dict[str, dict[str, str]] = defaultdict(dict)
    for row in verdicts:
        by_rec[row["rec_id"]][row["screener"]] = row["decision"]
    both = sorted(rec for rec, seen in by_rec.items() if "A" in seen and "B" in seen)
    if both:
        a = [by_rec[rec]["A"] for rec in both]
        b = [by_rec[rec]["B"] for rec in both]
        kappa, parts = cohens_kappa(a, b)
        disagreed = sum(1 for x, y in zip(a, b) if x != y)
        add(f"Records judged by both screeners: {len(both)}.")
        add("")
        add(f"- Cohen kappa A versus B: **{kappa:.3f}** ({interpret(kappa)})")
        add(f"- Observed agreement {parts['observed_agreement']}, "
            f"expected {parts['expected_agreement']}")
        add(f"- Screener A included {a.count('include')}, "
            f"screener B included {b.count('include')}")
        add(f"- Disagreements: {disagreed} "
            f"({100 * disagreed / len(both):.1f} per cent), all resolved by inclusion")
        add("")
    else:
        add("No record has a verdict from both screeners yet.")
        add("")

    single = sorted(rec for rec, seen in by_rec.items() if len(seen) == 1)
    if single:
        titles = {row["rec_id"]: row["title"] for row in records}
        add(f"**{len(single)} record(s) carry a verdict from only one screener** and are "
            f"therefore outside the agreement calculation. Named here so a reader can "
            f"check the judgement rather than take it on trust:")
        add("")
        for rec_id in single[:10]:
            only = next(iter(by_rec[rec_id]))
            add(f"- `{rec_id}`, screener {only} said "
                f"{by_rec[rec_id][only]}: {titles.get(rec_id, '(unknown title)')[:90]}")
        add("")

    reasons = Counter(row["reason_code"] for row in verdicts)
    add("| Reason code | Verdicts |")
    add("|---|---:|")
    for reason, count in reasons.most_common():
        add(f"| `{reason}` | {count} |")
    add("")

    if included:
        unanimous = sum(1 for row in included
                        if row.get("screening", {}).get("unanimous"))
        add(f"Of {len(included)} included records, {unanimous} were included by both "
            f"screeners and {len(included) - unanimous} on one screener's vote.")
        add("")

    calibration = queries.get("calibration", [])
    if calibration and verdicts:
        from .screen import find_calibration_record
        record_index = {row["rec_id"]: row for row in records}
        add("### Calibration items")
        add("")
        add("Expected verdicts were never shown to a screener; the comparison is made")
        add("here. A screener that misses one is reported, not retrained.")
        add("")
        add("| Reference | Expected | A | B |")
        add("|---|---|---|---|")
        for item in calibration:
            rec_id = find_calibration_record(item["ref"], record_index)
            got = by_rec.get(rec_id, {}) if rec_id else {}
            add(f"| `{item['ref']}` | {item['expected']} | "
                f"{got.get('A', 'not screened')} | {got.get('B', 'not screened')} |")
        add("")

    # ---------------------------------------------------------- retrieval
    if retrieval:
        add("## 4. Retrieval")
        add("")
        add("| Status | Records |")
        add("|---|---:|")
        for status, count in retrieval_by_status.most_common():
            add(f"| `{status}` | {count} |")
        add("")
        add("| Text source | Records |")
        add("|---|---:|")
        for source, count in Counter(row["text_source"] for row in retrieval).most_common():
            add(f"| `{source}` | {count} |")
        add("")

    # --------------------------------------------------------- extraction
    if schemes or rejected:
        add("## 5. Extraction and the quote gate")
        add("")
        add(f"- Verified dimension rows: **{len(schemes)}**")
        add(f"- Rows voided because a quote could not be located: **{len(rejected)}**")
        if schemes or rejected:
            total_rows = len(schemes) + len(rejected)
            add(f"- Void rate: {100 * len(rejected) / total_rows:.1f} per cent of "
                f"{total_rows} rows returned")
        modes = Counter(row.get("quote_match_mode", "") for row in schemes)
        add(f"- Quote match: {modes.get('exact', 0)} exact, "
            f"{modes.get('caseless', 0)} needed case to be ignored")
        over = sum(1 for row in schemes if row.get("quote_over_soft_cap"))
        add(f"- Quotes longer than 25 words, kept and flagged: {over}")
        from_abstract = sum(1 for row in schemes
                            if row.get("retrieval_status") == "abstract_only")
        add(f"- Rows verified against an abstract rather than a full text: "
            f"{from_abstract}")
        artifacts = sum(1 for row in schemes if row.get("has_extraction_artifact"))
        add(f"- Rows carrying a character PDF extraction lost, usually a dash "
            f"inside a label: {artifacts}")
        add("")
        if rejected:
            fault_counter = Counter(fault.split(" (")[0]
                                    for row in rejected for fault in row.get("faults", []))
            add("| Void reason | Rows |")
            add("|---|---:|")
            for fault, count in fault_counter.most_common(10):
                add(f"| {fault} | {count} |")
            add("")

        add("### Schemes by domain")
        add("")
        domain_of = {}
        for row in schemes:
            domain_of[row["scheme_id"]] = row["domain"]
        add("| Domain | Schemes | Dimension rows |")
        add("|---|---:|---:|")
        rows_per_domain = Counter(row["domain"] for row in schemes)
        schemes_per_domain = Counter(domain_of.values())
        for domain in sorted(schemes_per_domain):
            add(f"| {domain} | {schemes_per_domain[domain]} | "
                f"{rows_per_domain[domain]} |")
        add("")

        add("### Schemes by type and authority")
        add("")
        type_of = {row["scheme_id"]: row["artifact_type"] for row in schemes}
        auth_of = {row["scheme_id"]: row["authority"] for row in schemes}
        add("| Artifact type | Schemes |")
        add("|---|---:|")
        for kind, count in Counter(type_of.values()).most_common():
            add(f"| {kind} | {count} |")
        add("")
        add("| Authority | Schemes |")
        add("|---|---:|")
        for kind, count in Counter(auth_of.values()).most_common():
            add(f"| {kind} | {count} |")
        add("")
        with_artifact = sum(1 for scheme_id in schemes_kept
                            if next(row["machine_readable_artifact"] for row in schemes
                                    if row["scheme_id"] == scheme_id) != "none")
        add(f"Schemes pointing at a machine-readable artefact: {with_artifact} of "
            f"{len(schemes_kept)}.")
        add("")

    # -------------------------------------------------------- limitations
    add("## 6. Limitations")
    add("")
    add("- **Screener independence is partial.** Both screeners are the same model "
        "family working from differently worded criteria. Their agreement measures "
        "prompt stability more than it measures independent judgement. The human "
        "sample is the corrective, not the kappa between them.")
    add("- **Grey literature was not searched systematically.** Publisher author "
        "instructions, citation style manuals and institutional policies are in "
        "scope by type and enter only when a searched record points at them.")
    add("- **PDF extraction loses table structure.** A dimension stated only inside "
        "a table may have been missed, and a quote taken from one may have failed "
        "verification although the text is really there.")
    add("- **Semantic Scholar was not used**, because it rate-limits without an API "
        "key. Its coverage of computer science conference proceedings is better than "
        "Crossref's, so some HCI work may be missing.")
    add("- **One snowballing iteration.** A scheme cited only by papers two steps "
        "from the included set would not be reached.")
    add("")

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with io.open(REPORT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {REPORT} ({len(lines)} lines)")

    if faults:
        print("\nFLOW DOES NOT RECONCILE:")
        for fault in faults:
            print(f"  {fault}")
        return 1
    print("flow reconciles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
