"""Collect AI disclosure formulations from public software projects.

Two places a software project says an AI was involved:

1. Commit messages, including machine-written trailers. These are the closest
   thing the software world has to a standard disclosure format, and unlike a
   journal template nobody was told to use them.
2. Prose in README and documentation files, which is free wording.

Authentication goes through the `gh` CLI, so no token is stored in this
repository. Run `gh auth login` first.

Commit messages carry email addresses in their trailers. Those are redacted
before an item is built, and the redaction is recorded on the item.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import time

from common import Item, fetch, normalise_ws, window_around, write_items

RAW = "https://raw.githubusercontent.com/{repo}/HEAD/{path}"

COMMIT_TRIGGERS = [
    "Generated with Claude Code",
    "written with the help of AI",
    "AI-assisted commit",
    "generated by ChatGPT",
]

CODE_TRIGGERS = [
    ("parts of this project were generated", "README.md"),
    ("this documentation was written with", "README.md"),
    ("was written with the help of AI", "README.md"),
    ("we use AI tools to", "CONTRIBUTING.md"),
]

EMAIL_RE = re.compile(r"<[^<>@\s]+@[^<>\s]+>")


def redact_emails(text: str) -> tuple[str, bool]:
    redacted, count = EMAIL_RE.subn("<email redacted>", text)
    return redacted, count > 0


def gh_search(endpoint: str, query: str, per_page: int = 5) -> list[dict]:
    """Call the GitHub search API through the gh CLI."""
    cmd = [
        "gh", "api", "-X", "GET", f"search/{endpoint}",
        "-f", f"q={query}",
        "-f", f"per_page={per_page}",
    ]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=90)
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"[github] {endpoint} search failed: {exc}")
        return []
    if out.returncode != 0:
        print(f"[github] {endpoint} search failed: {out.stderr.strip()[:200]}")
        return []
    try:
        return json.loads(out.stdout).get("items", [])
    except ValueError:
        return []


def collect_commits(per_phrase: int = 4) -> list[Item]:
    items: list[Item] = []
    for phrase in COMMIT_TRIGGERS:
        hits = gh_search("commits", f'"{phrase}"', per_phrase)
        print(f"[github] commits {phrase!r}: {len(hits)} hits")
        for hit in hits:
            message = normalise_ws(hit.get("commit", {}).get("message", ""))
            text = window_around(message, phrase) or message
            text, was_redacted = redact_emails(text)
            note = f"found via phrase: {phrase}"
            if was_redacted:
                note += "; email addresses redacted"
            items.append(
                Item(
                    text_verbatim=text,
                    lang="en",
                    genre="software_project",
                    source_type="git_commit_message",
                    source_url=hit.get("html_url", ""),
                    source_date=(hit.get("commit", {}).get("author", {}).get("date", ""))[:10],
                    placement="commit message",
                    context_note=note,
                    license_note="public repository",
                )
            )
        time.sleep(2)  # search API allows 30 requests per minute
    return items


def collect_code(per_phrase: int = 4) -> list[Item]:
    items: list[Item] = []
    for phrase, filename in CODE_TRIGGERS:
        hits = gh_search("code", f'"{phrase}" filename:{filename}', per_phrase)
        print(f"[github] code {phrase!r} in {filename}: {len(hits)} hits")
        for hit in hits:
            repo = hit.get("repository", {}).get("full_name", "")
            path = hit.get("path", "")
            if not repo or not path:
                continue
            body = fetch(RAW.format(repo=repo, path=path))
            time.sleep(0.4)
            if not body:
                continue
            text = window_around(normalise_ws(body), phrase)
            if not text:
                continue
            text, was_redacted = redact_emails(text)
            note = f"file: {path}; found via phrase: {phrase}"
            if was_redacted:
                note += "; email addresses redacted"
            items.append(
                Item(
                    text_verbatim=text,
                    lang="en",
                    genre="software_project",
                    source_type="repository_documentation",
                    source_url=hit.get("html_url", ""),
                    placement=path,
                    context_note=note,
                    license_note="public repository",
                )
            )
        time.sleep(2)
    return items


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "data/corpus/corpus.jsonl"
    found = collect_commits() + collect_code()
    stats = write_items(out, found)
    print(f"[github] {stats}")
