"""Collect AI disclosure formulations from public software projects.

Two places a software project says an AI was involved:

1. Commit messages, including machine-written trailers. These are the closest
   thing the software world has to a standard disclosure format, and unlike a
   journal template nobody was told to use them.
2. Prose in README and documentation files, which is free wording.

Authentication goes through the `gh` CLI, so no token is stored in this
repository. Run `gh auth login` first.

Commit messages carry email addresses in their trailers. Those are redacted
before an item is built, and the redaction is recorded on the item.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import time

from common import Item, fetch, normalise_ws, window_around, write_items

RAW = "https://raw.githubusercontent.com/{repo}/HEAD/{path}"

COMMIT_TRIGGERS = [
    "Generated with Claude Code",
    "written with the help of AI",
    "AI-assisted commit",
    "generated by ChatGPT",
]

CODE_TRIGGERS = [
    ("parts of this project were generated", "README.md"),
    ("this documentation was written with", "README.md"),
    ("was written with the help of AI", "README.md"),
    ("we use AI tools to", "CONTRIBUTING.md"),
]

EMAIL_RE = re.compile(r"<[^<>@\s]+@[^<>\s]+>")


def redact_emails(text: str) -> tuple[str, bool]:
    redacted, count = EMAIL_RE.subn("<email redacted>", text)
    return redacted, count > 0


def prose_from_markdown(body: str) -> str:
    """Markdown to prose, with headings turned into sentence breaks.

    A README heading is navigation, not part of a formulation. Left in place
    it leaks into the extracted window, so each heading line becomes a period
    and the window then starts after it.
    """
    parts = []
    for line in body.splitlines():
        stripped = line.strip()
        parts.append("." if stripped.startswith("#") else line)
    return normalise_ws(" ".join(parts))


def trim_to_trigger_sentence(text: str, phrase: str) -> str:
    """Keep only the sentence that holds the trigger.

    What follows a disclosure sentence in a README is usually credits,
    guidelines or technical notes, and it sometimes carries personal names,
    which must never enter the corpus.
    """
    low = text.lower()
    idx = low.find(phrase.lower())
    if idx < 0:
        return ""
    ends = [e for e in (text.find(". ", idx), text.find("! ", idx), text.find("? ", idx)) if e != -1]
    end = min(ends) if ends else len(text)
    return text[: end + 1] if end < len(text) else text


def cut_at_bullet(text: str, phrase: str) -> str:
    """Stop at the next sub-commit bullet.

    A squashed merge lists every sub-commit as "* subject" lines; what comes
    after the trigger bullet is not part of its formulation.
    """
    low = text.lower()
    idx = low.find(phrase.lower())
    if idx < 0:
        return text
    cut = text.find(" * ", idx + len(phrase))
    return text[:cut] if cut != -1 else text


def strip_markdown(text: str) -> str:
    """Drop markdown decoration; formatting is not part of the wording."""
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\*\*?([^*]+)\*\*?", r"\1", text)
    return text.lstrip("*-#>`|~ .").rstrip("*-#>`|~ ")


def gh_search(endpoint: str, query: str, per_page: int = 5) -> list[dict]:
    """Call the GitHub search API through the gh CLI.

    The search API has an undocumented secondary limit that answers 403 after
    only a couple of queries, so on a rate-limit refusal we wait a minute and
    try the query once more instead of losing it.
    """
    cmd = [
        "gh", "api", "-X", "GET", f"search/{endpoint}",
        "-f", f"q={query}",
        "-f", f"per_page={per_page}",
    ]
    for attempt in range(2):
        try:
            out = subprocess.run(
                cmd, capture_output=True, timeout=90,
                encoding="utf-8", errors="replace",
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            print(f"[github] {endpoint} search failed: {exc}")
            return []
        if out.returncode == 0:
            try:
                return json.loads(out.stdout).get("items", [])
            except ValueError:
                return []
        if "rate limit" in out.stderr.lower() and attempt == 0:
            print("[github] rate limited, waiting 60 s and retrying once")
            time.sleep(60)
            continue
        print(f"[github] {endpoint} search failed: {out.stderr.strip()[:200]}")
        return []
    return []


def collect_commits(per_phrase: int = 4) -> list[Item]:
    items: list[Item] = []
    for phrase in COMMIT_TRIGGERS:
        hits = gh_search("commits", f'"{phrase}"', per_phrase)
        print(f"[github] commits {phrase!r}: {len(hits)} hits")
        for hit in hits:
            message = normalise_ws(hit.get("commit", {}).get("message", ""))
            text = window_around(message, phrase)
            if not text:
                continue
            text = cut_at_bullet(text, phrase)
            text, was_redacted = redact_emails(text)
            note = f"found via phrase: {phrase}"
            if was_redacted:
                note += "; email addresses redacted"
            items.append(
                Item(
                    text_verbatim=text,
                    lang="en",
                    genre="software_project",
                    source_type="git_commit_message",
                    source_url=hit.get("html_url", ""),
                    source_date=(hit.get("commit", {}).get("author", {}).get("date", ""))[:10],
                    placement="commit message",
                    context_note=note,
                    license_note="public repository",
                    trigger_phrase=phrase,
                )
            )
        time.sleep(30)  # the search API's secondary limit bites well before the 30/min primary one
    return items


def collect_code(per_phrase: int = 4) -> list[Item]:
    items: list[Item] = []
    for phrase, filename in CODE_TRIGGERS:
        hits = gh_search("code", f'"{phrase}" filename:{filename}', per_phrase)
        print(f"[github] code {phrase!r} in {filename}: {len(hits)} hits")
        for hit in hits:
            repo = hit.get("repository", {}).get("full_name", "")
            path = hit.get("path", "")
            if not repo or not path:
                continue
            body = fetch(RAW.format(repo=repo, path=path))
            time.sleep(0.4)
            if not body:
                continue
            text = window_around(prose_from_markdown(body), phrase)
            if not text:
                continue
            text = trim_to_trigger_sentence(text, phrase)
            if not text:
                continue
            text = strip_markdown(text)
            text, was_redacted = redact_emails(text)
            note = f"file: {path}; found via phrase: {phrase}"
            if was_redacted:
                note += "; email addresses redacted"
            items.append(
                Item(
                    text_verbatim=text,
                    lang="en",
                    genre="software_project",
                    source_type="repository_documentation",
                    source_url=hit.get("html_url", ""),
                    placement=path,
                    context_note=note,
                    license_note="public repository",
                    trigger_phrase=phrase,
                )
            )
        time.sleep(30)
    return items


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "data/corpus/corpus.jsonl"
    found = collect_commits() + collect_code()
    stats = write_items(out, found)
    print(f"[github] {stats}")
